class Painter:
    def __init__(self):
        ...

    def goto(self, x, y):
        ...

    def heading(self, h):
        ...

    def forward(self, length):
        ...

    def draw_rect(self, width, height, color):
        ...

    def draw_circle(self, x, y, radius, color):
        ...
